### ISSUE TITLE
Need help :: Wanted to create a tool in C# to encrypt and decrypt data in RSA

### ISSUE THREAD

**Issue by shubhamaryanite** [kashifsoofi/crypto-sandbox#10]
I am trying to create a tool in C# for RSA encryption and decryption. I am taking reference from ur RsaBcCrypto.cs file.
But I am getting key as input from user in "RichTextBox" in C# -
For example: input is feed in "RichTextBox" and it is 512 bytes RSA public key:
 MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ7VO7sLSNh1OTOHPJnr/vWRuYpZFVu9dEiplVeczx40brTpaPQL+JTWJuiMLVWBWFjlDL0OFLJM92qmKBDREpkCAwEAAQ=

I am not able to produce rsa public key from the above given input. I am receiving input as "RichTextBox.Text"
Can u pls help me with that
and also the method to create

**Comment by kashifsoofi** [comment]
@shubhamaryanite you need to determine the key format and load it into RsaPublicKeyParameters, its not a json
